export const CREATE_SHORT_LINK = 'CREATE_SHORT_LINK';
export const UPDATE_SHORT_LINK = 'UPDATE_SHORT_LINK';
export const DELETE_SHORT_LINK = 'DELETE_SHORT_LINK';
export const CREATE_SHORT_LINK_COLLECTION = 'CREATE_SHORT_LINK_COLLECTION';
export const UPDATE_SHORT_LINK_COLLECTION = 'UPDATE_SHORT_LINK_COLLECTION';
export const DELETE_SHORT_LINK_COLLECTION = 'DELETE_SHORT_LINK_COLLECTION';

export const GET_OWNED_LINKS = 'GET_OWNED_LINKS';
export const SET_OWNED_LINKS = 'SET_OWNED_LINKS';

export const GET_OWNED_LINK_COLLECTIONS = 'GET_OWNED_LINK_COLLECTIONS';
export const SET_OWNED_LINK_COLLECTIONS = 'SET_OWNED_LINK_COLLECTIONS';

export const REMOVE_OWNED_LINK = 'REMOVE_OWNED_LINK';
export const ADD_CREATED_LINK = 'ADD_CREATED_LINK';

export const GET_LINK_COLLECTION = 'GET_LINK_COLLECTION';
export const SET_LINK_COLLECTION = 'SET_LINK_COLLECTION';

export const SET_HEADING = 'SET_HEADING';
export const SET_SUBHEADING = 'SET_SUBHEADING';
export const SET_LINK_TEXT = 'SET_LINK_TEXT';
export const SET_LINK_REDIRECT_URL = 'SET_LINK_REDIRECT_URL';
export const SET_LINK_SHOULD_OPEN_IN_NEW_TAB = 'SET_LINK_SHOULD_OPEN_IN_NEW_TAB';
export const SET_LINK_ICON = 'SET_LINK_ICON';
export const ADD_EMPTY_LINK_TO_ACTIVE_COLLECTION = 'ADD_EMPTY_LINK_TO_ACTIVE_COLLECTION';
export const REMOVE_LINK_FROM_ACTIVE_COLLECTION = 'REMOVE_LINK_FROM_ACTIVE_COLLECTION';
export const RECORD_LINK_CLICK = 'RECORD_LINK_CLICK';

export const LOGOUT = 'LOGOUT';
export const PROCESS_LOGIN = 'PROCESS_LOGIN';
export const CLOSE_ACCOUNT = 'CLOSE_ACCOUNT';

export const ADD_SUCCESS_TOAST = 'ADD_SUCCESS_TOAST';
export const ADD_FAILURE_TOAST = 'ADD_FAILURE_TOAST';
