name: Deploy

permissions:
  id-token: write

on:
  push:
    paths-ignore:
      - ".github/workflows/lighthouse.yml"
      - "lighthouse.js"
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::388474961170:role/github-actions-oidc
          aws-region: us-east-1

      - name: Build & Deploy
        run: |
          npm install
          npm run deploy

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: build/

#      - name: Lighthouse Report
